// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	mysql "github.com/go-sql-driver/mysql"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3cdacd76DecodeModels(in *jlexer.Lexer, out *ScComment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint(in.Uint())
		case "product_ID":
			out.ProductID = uint(in.Uint())
		case "release_ID":
			out.ReleaseID = uint(in.Uint())
		case "user_ID":
			out.UserID = uint(in.Uint())
		case "comment_text":
			out.CommentText = string(in.String())
		case "comment_grade":
			out.CommentGrade = int8(in.Int8())
		case "comment_Date":
			easyjson3cdacd76DecodeGithubComGoSqlDriverMysql(in, &out.CommentDate)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3cdacd76EncodeModels(out *jwriter.Writer, in ScComment) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ID\":")
	out.Uint(uint(in.ID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"product_ID\":")
	out.Uint(uint(in.ProductID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"release_ID\":")
	out.Uint(uint(in.ReleaseID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"user_ID\":")
	out.Uint(uint(in.UserID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"comment_text\":")
	out.String(string(in.CommentText))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"comment_grade\":")
	out.Int8(int8(in.CommentGrade))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"comment_Date\":")
	easyjson3cdacd76EncodeGithubComGoSqlDriverMysql(out, in.CommentDate)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScComment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3cdacd76EncodeModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScComment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3cdacd76EncodeModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScComment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3cdacd76DecodeModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScComment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3cdacd76DecodeModels(l, v)
}
func easyjson3cdacd76DecodeGithubComGoSqlDriverMysql(in *jlexer.Lexer, out *mysql.NullTime) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Time).UnmarshalJSON(data))
			}
		case "Valid":
			out.Valid = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3cdacd76EncodeGithubComGoSqlDriverMysql(out *jwriter.Writer, in mysql.NullTime) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Time\":")
	out.Raw((in.Time).MarshalJSON())
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Valid\":")
	out.Bool(bool(in.Valid))
	out.RawByte('}')
}
