// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2564ebc2DecodeModels(in *jlexer.Lexer, out *ScUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint(in.Uint())
		case "user_name":
			out.UserName = string(in.String())
		case "avatar_url":
			out.AvatarURL = string(in.String())
		case "mail":
			out.Mail = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2564ebc2EncodeModels(out *jwriter.Writer, in ScUser) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ID\":")
	out.Uint(uint(in.ID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"user_name\":")
	out.String(string(in.UserName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"avatar_url\":")
	out.String(string(in.AvatarURL))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"mail\":")
	out.String(string(in.Mail))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScUser) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2564ebc2EncodeModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScUser) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2564ebc2EncodeModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScUser) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2564ebc2DecodeModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScUser) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2564ebc2DecodeModels(l, v)
}
